server:
    port: 8888
spring:
    datasource:
        # driver-class-name: com.mysql.jdbc.Driver
        # url: jdbc:mysql://localhost:3306/blog
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/blog
        username: blog_user
        password: blog_password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

